### ISSUE TITLE
Quest3 ALXR client crash

### ISSUE THREAD

**Issue by Wizard-one** [korejan/ALVR#109]
## Description

Hi! After  [v0.37.0+nightly.2024.05.19](https://github.com/korejan/ALXR-nightly/releases/tag/v0.37.0%2Bnightly.2024.05.19) removes quest oxr loader, I guess quest3 use `alxr-client.apk` as a client app. However, the app never makes it past the default loading screen after this version. Or is Quest out of support?

**Comment by korejan** [comment]
@Wizard-one hi, yes this is the version to use from now on, quest offically works with the standard/khronos OXR android loader. Meta is no longer releasing new versions of their vendor specific loader and has been removed in their latest sdk, you can read about it [here](https://developer.oculus.com/downloads/package/oculus-openxr-mobile-sdk/?locale=en_GB).

I just tested the latest nightly build (v0.38.1) it is working on my Quest 3, which firmware version is yours on? if it is below v62 it will not work according to the changelog in the link

**Comment by Wizard-one** [comment]
Oh, After I fix some network issue, I upgrade my firmware to V65, it works perfectly!

Thank you, much appreciated
