### ISSUE TITLE
Pico ALXR client will not install onto Pico Neo 2 due to APK not being compatible with android 8.1

### ISSUE THREAD

**Issue by CaiVR** [korejan/ALVR#29]
Trying to get ALXR client installed through both ADB and the headset storage itself without success. I've tried everything within my immediate scope to get it installed, but as far as I can tell the client APKs are all built for android 9, not the 8.1 that the Neo 2 is running.

This is the error message I get with ADB:
`adb: failed to install alxr-client-pico.apk: Failure [INSTALL_FAILED_OLDER_SDK: Failed parse during installPackageLI: /data/app/vmdl727685437.tmp/base.apk (at Binary XML file line #1): Requires newer sdk version #28 (current version is #27)]`

I just want clarification on the issue because I feel I'm missing something here. Any help would be appreciated, thanks!

**Comment by korejan** [comment]
Forgot to add, yes currently alxr has minimum sdk api level of 29. It maybe possible to bring down a bit lower but it's something I'll need to look into and as I mentioned Neo 2 lacks an OpenXR runtime right now.
