### ISSUE TITLE
compile problem

### ISSUE THREAD

**Issue by herehero** [korejan/ALVR#33]
I compile the project follow the wiki spec.
The compile process always blocked.
I only succeed one or twice.

the lates code compile log like this:
  |
1 | use alvr_common::ALVR_VERSION;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: unused import: `DictionaryDefault`
 --> alvr\session\src\settings.rs:4:23
  |
4 | use settings_schema::{DictionaryDefault, EntryData, SettingsSchema, Switch, SwitchDefault};
  |                       ^^^^^^^^^^^^^^^^^

warning: `alvr_session` (lib) generated 2 warnings
warning: field is never read: `stream_id`
   --> alvr\sockets\src\stream_socket\mod.rs:168:5
    |
168 |     stream_id: StreamId,
    |     ^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default

warning: `alvr_sockets` (lib) generated 1 warning
    Building [=======================> ] 262/266: alxr-...

I try many times,it always blocked like that and never finished. 
It just blocked,didn't print any log.
May I have some information from you to help me solve the problem?
thanks.

**Comment by korejan** [comment]
@herehero Hey, is trying to make one of the Android builds on windows?

**Comment by hero-jing** [comment]
> @herehero Hey, are you trying to make one of the Android builds on windows?

yes

**Comment by korejan** [comment]
I believe this is an issue with cargo-apk only on windows, the workaround is to either kill the (open)jdk process when there's %0 CPU activity or open alxr-engine-sys/android in android-studio, build it once there and leave it open, then build as normal.

**Comment by hero-jing** [comment]
> I believe this is an issue with cargo-apk only on windows, the workaround is to either kill the (open)jdk process when there's %0 CPU activity or open alxr-engine-sys/android in android-studio, build it once there and leave it open, then build as normal.

It realy workd.Your suggestion has helped a lot.
thanks.
