### ISSUE TITLE
Pico neo 3 Pro Eye cant run xrCreateSession，XrResult failure [XR_ERROR_VALIDATION_FAILURE]

### ISSUE THREAD

**Issue by osdalong** [korejan/ALVR#34]
Hi sirs：
I got a Pico neo 3 Pro Eye，and install v0.10.0/alxr-client-pico.apk  by adb.  

It cant run xrCreateSession. and one can help me?

By the way,  has  the alxr found the controllers?  SteamVR which version is 1.23.7 only found the HMD, cant find the 6dof controllers.

09-06 10:05:12.735  6084  6108 I PxrCompositor: pxrInitialize PVR_TRACKING_SERVICE StartTracking = 0
09-06 10:05:12.735  6084  6108 I VrServiceApi: trying to open libpxrnotification.pxr.so
09-06 10:05:12.736  6084  6084 I Thread-1: type=1400 audit(0.0:4453): avc: denied { call } for scontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tcontext=u:r:pxrhmdservice:s0 tclass=binder permissive=1
09-06 10:05:12.736  6084  6108 I VrServiceApi: dlopen ok
09-06 10:05:12.736  6084  6108 I VrServiceApi: dlsym for pico_addPxrCallback ok
09-06 10:05:12.736  6084  6108 I VrServiceApi: dlsym for pico_sendMessage ok
09-06 10:05:12.736  6084  6108 I VrServiceApi: dlsym for pico_removeCallback ok
09-06 10:05:12.736  6084  6108 D PxrNotificationClient:   [getInstance] ,vector length:0
09-06 10:05:12.736  6084  6108 D PxrNotificationClient:   [IPxrNotificationClient]
09-06 10:05:12.737   570   570 E SELinux : avc:  denied  { find } for service=pxr_notification pid=6084 uid=10185 scontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tcontext=u:object_r:pxr_notification_service:s0 tclass=service_manager permissive=1
09-06 10:05:12.737  6084  6108 W PxrNotificationClient: open client removeCallback
09-06 10:05:12.737  6084  6108 D PxrNotificationClient:   [addPxrCallback] ,vector length:1  ,action:com.notificaton.test
09-06 10:05:12.737  6084  6108 D PxrNotificationClient:   [addPxrCallback] ,mActionCallbackMap length:1  ,action:com.notificaton.test
09-06 10:05:12.737  2392  2426 I PxrNotificationService: pcb is com.pvr.pxrnotification.aidl.IPxrNotificationCallback$Stub$Proxy@1eb4311 ,action:com.notificaton.test ,type:1
09-06 10:05:12.737  2392  2426 I PxrNotificationService: >>addPxrCallback action:com.notificaton.test,type:1
09-06 10:05:12.737  2392  2426 V PxrNotificationService: addCallBackToMap..callingPid:6084
09-06 10:05:12.737  6084  6108 W PxrNotificationClient: open client sendMessage
09-06 10:05:12.737  6084  6108 W PxrNotificationClient: IPxrNotificationClient::sendPxrMessage com.notificaton.test 1 test 2 (null)
09-06 10:05:12.737  2392  2426 D PxrNotificationService: sendPxrMessage  action com.notificaton.test ,value1:test ,value2:2 ,ext: ,mPvrCallbacks.size():11
09-06 10:05:12.737  2392  2426 D PxrNotificationService: notifyCallbackEvent  action: com.notificaton.test ,mMap.size:1 ,value1:testvalue2:2
09-06 10:05:12.737  2392  2426 I PxrNotificationService: mMap key:com.notificaton.testmMap ready send: ,value:com.pvr.pxrnotification.aidl.IPxrNotificationCallback$Stub$Proxy@1eb4311 ,actual send value:com.pvr.pxrnotification.aidl.IPxrNotificationCallback$Stub$Proxy@1eb4311
09-06 10:05:12.737  6084  6100 D PxrNotificationClient: IPxrNotificationClient::onEventChanged, value1:test, value2:2, ext: 
09-06 10:05:12.737  6084  6100 D PxrNotificationClient: IPxrNotificationClient::onEventChangedWithAction, action:com.notificaton.test, value1:test, value2:2, ext1: ,ext2:ext2 ,ext3:ext3
09-06 10:05:12.737  6084  6100 E PxrNotificationClient: onEventChangedWithAction:   key :com.notificaton.test
09-06 10:05:12.737  6084  6100 E PxrNotificationClient: onEventChangedWithAction:   key :com.notificaton.test send callback msg
09-06 10:05:12.737  6084  6100 I PxrCompositor: pxrInitialize PvrService StartVrMode test,id 2
09-06 10:05:12.737  6084  6108 W PxrNotificationClient: open client removeCallback
09-06 10:05:12.737  6084  6108 D PxrNotificationClient:   [addPxrCallback] ,vector length:2  ,action:com.pxr.ipdstatus.change
09-06 10:05:12.737  6084  6108 D PxrNotificationClient:   [addPxrCallback] ,mActionCallbackMap length:2  ,action:com.pxr.ipdstatus.change
09-06 10:05:12.738  2392  2426 I PxrNotificationService: pcb is com.pvr.pxrnotification.aidl.IPxrNotificationCallback$Stub$Proxy@fc0ec76 ,action:com.pxr.ipdstatus.change ,type:1
09-06 10:05:12.738  2392  2426 I PxrNotificationService: >>addPxrCallback action:com.pxr.ipdstatus.change,type:1
09-06 10:05:12.738  2392  2426 V PxrNotificationService: addCallBackToMap..callingPid:6084
09-06 10:05:12.738   570   570 E SELinux : avc:  denied  { find } for service=pxrhmdservice pid=6084 uid=10185 scontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tcontext=u:object_r:pxrhmdservice_service:s0 tclass=service_manager permissive=1
09-06 10:05:12.740  6084  6108 I PxrProxyServiceClient: Call <PvrServiceClient> done.
09-06 10:05:12.740  6084  6108 I PxrProxyServiceClient: Call <getPXRModule> - instance=0x70d6f2d7c0.
09-06 10:05:12.740  6084  6108 I PxrCompositor: hmdClientStatusCallback 0
09-06 10:05:12.740  6084  6108 I PxrCompositor: onPvrClientStatusCallbackExt status = 0
09-06 10:05:12.740  6084  6108 I PxrProxyServiceClient: Call <setClientEventCallBack> - pvrserviceclient=0x70d6f2d7c0.
09-06 10:05:12.740  6084  6108 E PxrRuntime: Could not load or create config file no $HOME or $XDG_CONFIG_HOME env variables defined
09-06 10:05:12.740  6084  6108 W PxrRuntime: No config file!
09-06 10:05:12.740  6084  6108 E PxrRuntime: auto create hand left
09-06 10:05:12.741  6084  6108 W PxrRuntime: pico_device compositor handle = 0x9a8394209d7aab47
09-06 10:05:12.744  6084  6108 W PxrRuntime: pico_device inputmanager handle = 0x5821806c060f46f1
09-06 10:05:12.744  6084  6108 E PxrRuntime: Get function<p_GetPhyControllerConnectState> OK 
09-06 10:05:12.744  6084  6108 E LogConfig: get_config LogLevelBycom = 4.000000
09-06 10:05:12.744  6084  6108 E LogConfig: Compositor so file open,minLogLevel = 6
09-06 10:05:12.744  6084  6108 E LogConfig: getConfigMiniLevel:6
09-06 10:05:12.744  6084  6108 I InputDeviceManager: InputDeviceManager PxrInputManager xrVersion:  R2.0.1.5
09-06 10:05:12.744  6084  6108 I ConfigPropertyApi: trying to open libconfigurationclient.so
09-06 10:05:12.744  6084  6108 I ConfigPropertyApi: dlopen ok
09-06 10:05:12.744  6084  6108 I ConfigPropertyApi: dlsym for getPVRModule ok
09-06 10:05:12.745  2300  2372 D greenDAO: Values for query: [sdk_controller_type]
09-06 10:05:12.752  2300  2372 D greenDAO: Values for query: [sdk_controller_type]
09-06 10:05:12.753  2300  2372 D ConfigServerService:(a.java:79): getConfigProperty: params [ pkg : com.example.config pid :6084 type : 0, configName : sdk_controller_type , token:  ]
09-06 10:05:12.753  2300  2372 D ConfigServerService:(a.java:79):  , resultData : 5
09-06 10:05:12.753  6084  6108 E InputDeviceManager: get deviceModel type  5 .
09-06 10:05:12.755  6084  6108 E InputDeviceManager: pico_device libpxrcontorlserviceclient handle = 0x0
09-06 10:05:12.756  6084  6108 E Stationclient: L1:[SetLogLevel] set Log level : 1
09-06 10:05:12.756  6084  6108 E Stationclient: L1:get loglevel:0, 0
09-06 10:05:12.756  6084  6108 E Stationclient: L1:[StationClient]
09-06 10:05:12.757   570   570 E SELinux : avc:  denied  { find } for service=PicoStation-new pid=6084 uid=10185 scontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tcontext=u:object_r:PicoStation-new_service:s0 tclass=service_manager permissive=1
09-06 10:05:12.757  6084  6108 E Stationclient: L1:ben~~~~~~~~~33333
09-06 10:05:12.757   911   911 E Stationservice: L1:lock in AddServiceListener
09-06 10:05:12.757   911   911 E Stationservice: L1:unlock in AddServiceListener
09-06 10:05:12.757  6084  6108 E Stationclient: L1:ben~~~~~~~~~44444
09-06 10:05:12.757  6084  6108 E Stationclient: L1:DeathNotifier create
09-06 10:05:12.757  6084  6108 E Stationclient: L1:ben~~~~~~~~~55555
09-06 10:05:12.757  6084  6108 E Stationclient: L1:get motor flag:0, 0
09-06 10:05:12.758  6084  6108 E Stationclient: L1:initSharedMemory, mmap_fd=69
09-06 10:05:12.758  6084  6108 E Stationclient: L1:initSharedMemory, mmap_fd=69, mmap_addr=0x519e7000
09-06 10:05:12.758  6084  6108 E Stationclient: L1:SetConnectCallback!
09-06 10:05:12.758  6084  6108 E Stationclient: L1:SetDisconnectCallback!
09-06 10:05:12.758  6084  6108 E Stationclient: L1:SetOTACallback!
09-06 10:05:12.758  6084  6108 E Stationclient: L1:SetUnbondCallback!
09-06 10:05:12.758  6084  6108 E Stationclient: L1:SetGetCV3ControllerKEYCallback!
09-06 10:05:12.758  6084  6108 E Stationclient: L1:SetFWOTACallback!
09-06 10:05:12.759   570   570 E SELinux : avc:  denied  { find } for service=virtual_input pid=6084 uid=10185 scontext=u:r:untrusted_app:s0:c185,c256,c512,c768 tcontext=u:object_r:virtual_input_service:s0 tclass=service_manager permissive=1
09-06 10:05:12.759  6084  6108 I PvrVirtualInputClient: pvrVirtualInputCreate 0x70488fa068
09-06 10:05:12.759  6084  6108 E InputDeviceManager: Before VirtualHand Tracking CreateClient NULL,0x70389fc570 0x0
09-06 10:05:12.760  6084  6108 W PxrNotificationClient: open client removeCallback
09-06 10:05:12.760  6084  6108 D PxrNotificationClient:   [addPxrCallback] ,vector length:3  ,action:action.configure.change.notify.all
09-06 10:05:12.760  6084  6108 D PxrNotificationClient:   [addPxrCallback] ,mActionCallbackMap length:3  ,action:action.configure.change.notify.all
09-06 10:05:12.760  2392  2426 I PxrNotificationService: pcb is com.pvr.pxrnotification.aidl.IPxrNotificationCallback$Stub$Proxy@674d277 ,action:action.configure.change.notify.all ,type:0
09-06 10:05:12.760  2392  2426 I PxrNotificationService: >>addPxrCallback action:action.configure.change.notify.all,type:0
09-06 10:05:12.760  2392  2426 V PxrNotificationService: addCallBackToMap..callingPid:6084
09-06 10:05:12.760  6084  6108 W PxrRuntime: p_registerInputDeviceConnectCallback
09-06 10:05:12.760  6084  6108 W PxrRuntime: p_registerInputDeviceConnectCallback
09-06 10:05:12.760  6084  6108 W PxrRuntime: p_RegisterHandTrackingHandHomeCallback
09-06 10:05:12.760  6084  6108 W PxrRuntime: p_RegisterHandTrackingHandHomeCallback
09-06 10:05:12.760  6084  6108 W PxrRuntime: pico_device_create succeeds!
09-06 10:05:12.760  6084  6108 E PxrRuntime: auto create hand right
09-06 10:05:12.761  6084  6108 W PxrRuntime: pico_device compositor handle = 0x9a8394209d7aab47
09-06 10:05:12.761  6084  6108 W PxrRuntime: pico_device inputmanager handle = 0x5821806c060f46f1
09-06 10:05:12.761  6084  6108 E PxrRuntime: Get function<p_GetPhyControllerConnectState> OK 
09-06 10:05:12.761  6084  6108 E InputDeviceManager: connectStatusCallbackFunc already register
09-06 10:05:12.761  6084  6108 W PxrRuntime: p_registerInputDeviceConnectCallback
09-06 10:05:12.761  6084  6108 W PxrRuntime: p_registerInputDeviceConnectCallback
09-06 10:05:12.761  6084  6108 W PxrRuntime: p_RegisterHandTrackingHandHomeCallback
09-06 10:05:12.761  6084  6108 W PxrRuntime: p_RegisterHandTrackingHandHomeCallback
09-06 10:05:12.761  6084  6108 W PxrRuntime: pico_device_create succeeds!
09-06 10:05:12.761  6084  6108 W PxrRuntime: No config file!
09-06 10:05:12.761  6084  6108 E PxrRuntime: No tracking node
09-06 10:05:12.761  6084  6108 W PxrRuntime: callback register_eventcallback   
09-06 10:05:12.761  6084  6108 W PxrRuntime: callback register_eventcallback   
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrt_gfx_provider_create_system: 0x6fe8943f80
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.create_swapchain        = 0x6fe6e474f4
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.create_swapchain_ext    = 0x6fe6e471ac
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.poll_events             = 0x6fe6e479b8
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.prepare_session         = 0x6fe6e47af8
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.begin_session           = 0x6fe6e47c44
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.end_session             = 0x6fe6e48bb8
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.wait_frame              = 0x6fe6e49144
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.begin_frame             = 0x6fe6e491b4
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.discard_frame           = 0x6fe6e491dc
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.layer_begin             = 0x6fe6e4963c
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.layer_stereo_projection = 0x6fe6e4985c
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.layer_quad              = 0x6fe6e4a228
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.layer_cube              = 0x6fe6e4a9a4
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.layer_cylinder          = 0x6fe6e4a9ac
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.layer_equirect          = 0x6fe6e4ad88
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.layer_commit            = 0x6fe6e4b27c
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.destroy                 = 0x6fe6e492c8
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.set_ipd                 = 0x6fe6e440bc
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_ipd                 = 0x6fe6e44248
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.set_tracking_ipd_enabled= 0x6fe6e4430c
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_tracking_ipd_enabled= 0x6fe6e44140
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_eye_tracking_autoIPD= 0x6fe6e44518
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_stencilmesh         = 0x6fe6e44930
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_frustum_parameters  = 0x6fe6e45084
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.set_frustum_parameters  = 0x6fe6e44b84
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_config              = 0x6fe6e451a4
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_configs             = 0x6fe6e456c4
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.set_config              = 0x6fe6e411ec
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.set_configs             = 0x6fe6e461c4
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.reset_sensor            = 0x6fe6e40d60
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.set_tracking_mode       = 0x6fe6e466d4
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_eyetracking_data    = 0x6fe6e4674c
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_tracking_mode       = 0x6fe6e46714
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_foveation_configs   = 0x6fe6e462a4
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.set_controller_position = 0x6fe6e4e848
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.boundary_test_node      = 0x6fe6e4e874
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.boundary_test_point     = 0x6fe6e4e980
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_boundary_geometry   = 0x6fe6e4eac0
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_boundarydimensions  = 0x6fe6e4eaec
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_seethrough_data     = 0x6fe6e4eb24
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.invoke_functions        = 0x6fe6e4eb88
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.set_performance_level   = 0x6fe6e46a20
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_performance_level   = 0x6fe6e46a94
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_foveation_image     = 0x6fe6e4d530
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.get_mrc_pose     = 0x6fe6e4ddf8
09-06 10:05:12.761  6084  6108 E PxrRuntime: xrcn->base.set_mrc_pose     = 0x6fe6e4dec0
09-06 10:05:12.761  6084  6108 E PxrRuntime: Doing init 0x6fe8943f80
09-06 10:05:12.762  6084  6108 V PxrLoader: Verbose [GENERAL | xrCreateInstance | PxrLoader] : Completed loader terminator
09-06 10:05:12.762  6084  6108 I PxrLoader: Info [GENERAL | xrCreateInstance | PxrLoader] : LoaderInstance::CreateInstance succeeded with 0 layers enabled and runtime interface - created instance = 0x00000070389e6c00
09-06 10:05:12.762  6084  6108 V PxrLoader: Verbose [GENERAL | xrCreateInstance | PxrLoader] : Completed loader trampoline
09-06 10:05:12.762  6084  6108 V alxr-client: [10:05:12.762][Info   ] Instance RuntimeName=Pico(XRT) by Pico et al 'cee08073' RuntimeVersion=3.0.1
09-06 10:05:12.762  6084  6108 V alxr-client: [10:05:12.762][Info   ] Available View Configuration Types: (1)
09-06 10:05:12.762  6084  6108 V alxr-client: [10:05:12.762][Info   ] Available Environment Blend Mode count : (1)
09-06 10:05:12.762  6084  6108 V alxr-client: [10:05:12.762][Info   ] Environment Blend Mode (XR_ENVIRONMENT_BLEND_MODE_OPAQUE) : (Selected)
09-06 10:05:12.762  6084  6108 V alxr-client: [10:05:12.762][Info   ] Using Vulkan version: 1.1
09-06 10:05:12.771  6084  6108 D vulkan  : searching for layers in '/data/app/com.alvr.alxr_client-hqIIIHas0l_QRbX30rupIw==/lib/arm64'
09-06 10:05:12.772  6084  6108 D vulkan  : searching for layers in '/data/app/com.alvr.alxr_client-hqIIIHas0l_QRbX30rupIw==/base.apk!/lib/arm64-v8a'
09-06 10:05:12.778  6084  6108 I AdrenoVK-0: ===== BEGIN DUMP OF OVERRIDDEN SETTINGS =====
09-06 10:05:12.778  6084  6108 I AdrenoVK-0: ===== END DUMP OF OVERRIDDEN SETTINGS =====
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: QUALCOMM build          : 70fbc48e4e, I30f6cedc70
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: Build Date              : 06/15/21
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: Shader Compiler Version : EV031.35.14.00
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: Local Branch            : 
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: Remote Branch           : refs/tags/AU_LINUX_ANDROID_LA.UM.8.12.C3.10.00.00.670.284
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: Remote Branch           : NONE
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: Reconstruct Branch      : NOTHING
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: Build Config            : S P 8.0.12 AArch64
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: Driver Path             : /vendor/lib64/hw/vulkan.kona.so
09-06 10:05:12.779  6084  6108 I AdrenoVK-0: Driver Version          : 0579.0
09-06 10:05:12.780  6084  6108 W PxrRuntime: Did not find runtime suggested GPU, fall back to GPU 0
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded vertex shader
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded fragment shader
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded vertex shader
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded fragment shader
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded vertex shader
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded fragment shader
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded vertex shader
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded fragment shader
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded vertex shader
09-06 10:05:12.784  6084  6108 V alxr-client: [10:05:12.784][Info   ] Loaded fragment shader
09-06 10:05:12.784  6084  6108 E PxrRuntime: (createInfo->next->type) doesn't contain a valid graphics binding structs
09-06 10:05:12.784  6084  6108 E alxr-client: [10:05:12.784][Error  ] XrResult failure [XR_ERROR_VALIDATION_FAILURE]
09-06 10:05:12.784  6084  6108 E alxr-client:     Origin: xrCreateSession(m_instance, &createInfo, &m_session)
09-06 10:05:12.784  6084  6108 E alxr-client:     Source: /home/runner/work/ALVR/ALVR/alvr/openxr-client/alxr-engine-sys/cpp/ALVR-OpenXR-Engine/src/alxr_engine/openxr_program.cpp:1292
09-06 10:05:12.784  6084  6107 I RustStdoutStderr: WARNING in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: LOG in xrCreateInstance: WARNING in xrGetVulkanGraphicsDeviceKHR: XR_ERROR_VALIDATION_FAILURE: xrCreateSession[10:05:12.784][Error  ] XrResult failure [XR_ERROR_VALIDATION_FAILURE]
09-06 10:05:12.784  6084  6107 I RustStdoutStderr:     Origin: xrCreateSession(m_instance, &createInfo, &m_session)
09-06 10:05:12.784  6084  6107 I RustStdoutStderr:     Source: /home/runner/work/ALVR/ALVR/alvr/openxr-client/alxr-engine-sys/cpp/ALVR-OpenXR-Engine/src/alxr_engine/openxr_program.cpp:1292
09-06 10:05:12.785  6084  6107 I RustStdoutStderr: successfully shutdown.
09-06 10:05:12.785   904  6118 I EyeTrackingService: onEventChange, activity_status activityResuming:com.alvr.alxr_client,android.app.NativeActivity
09-06 10:05:12.786  1037  1877 I chatty  : uid=1000(system) Binder:1037_5 expire 1 line
09-06 10:05:12.787   906  6120 I PxrHmdService: Call <pvrManagerCallBack> - onEventChange:key=activity_status value=activityResuming:com.alvr.alxr_client,android.app.NativeActivity
09-06 10:05:12.788  6084  6084 I PxrCompositor: PXRSDK_LC pxr_onActivityPaused_native
09-06 10:05:12.788  6084  6084 I PxrCompositor: PXRSDK_LC_MSG pxr_onActivityPaused_native, push to Queue:FOCUSED->VISIBLE->SYNCHRONIZED->STOPPING
09-06 10:05:12.788  6084  6084 D ActivityThread: [FEAT_UI_FIRST_WHEN_LAUNCH_APP][0] OnPause setUIFirstSched tid = 6084 processname = com.alvr.alxr_client

**Comment by osdalong** [comment]
PxrRuntime xrVersion is  R2.0.4.10.

09-06 10:05:12.485  6084  6108 W PxrRuntime: PxrRuntime xrVersion: R2.0.4.10

**Comment by korejan** [comment]
Hey, which firmware version are you using? for the non-link variants (including Pro eye), v4.8.x is confirmed working, please check if you have any updates.

**Comment by osdalong** [comment]
@korejan Thank you for you reply.

I had check my HMD,there only a PUI is 4.6.13.  No firmware version was showed, and there are no update for my HMD.

**Comment by feilong9m51** [comment]
@korejan  
can you  provide the v4.8.x  firmware version to me ? thank you

**Comment by osdalong** [comment]
@korejan I had got the version 4.8.x ,I will update it ASAP.  thanks!

**Comment by osdalong** [comment]
> @korejan Thank you for you reply.
> 
> I had check my HMD,there only a PUI is 4.6.13. No firmware version was showed, and there are no update for my HMD.


the device in china are not suggested to update include Pro and Pro Eye.

**Comment by korejan** [comment]
> > @korejan Thank you for you reply.
> > I had check my HMD,there only a PUI is 4.6.13. No firmware version was showed, and there are no update for my HMD.
> 
> the device in china are not suggested to update include Pro and Pro Eye.

Where did you get this info? sounds strange as the update notes in neo are in chinese. There is one Pro eye user who was on this version and wasn't able to get the update until they wrote that they resetted the device, another user with a plain chinese neo 3 said they recieved the update after rebooting the device. Sorry that is all i know without owning the device

@feilong9m51

**Comment by korejan** [comment]
This was from a non-pro Chinese neo 3 user on the alvr discord server but as I mentioned there was a pro eye user who managed to get it after resetting the device but they did mention it was European?
![unknown-4](https://user-images.githubusercontent.com/64199710/188828385-17e70629-05af-4376-a9a9-30feb038846d.png)

**Comment by osdalong** [comment]
@korejan 
I didnot get this FOTA update tip.
![](https://user-images.githubusercontent.com/64199710/188828385-17e70629-05af-4376-a9a9-30feb038846d.png)


the chinese update web is below. The version 4.8.16 is only for Pico Neo3. not for Pico Neo3 Pro, Pico Neo3 Eye( Chinese:本次升级仅针对Pico Neo3设备，Pico Neo3 Pro、Pico Neo3 Eye设备请不要升级此版本。)
https://www.pico-interactive.com/cn/puirom.html

the global update web, it looks can be applied for Pro Eye.
https://www.picoxr.com/global/software/pico-os

**Comment by osdalong** [comment]
the chinese Pro Eye is differen to global  Pro Eye, so there is no update 4.8.x for me.

**Comment by korejan** [comment]
> the chinese Pro Eye is differen to global Pro Eye, so there is no update 4.8.x for me.

You can not install the version from global website? 4.7.5 also works but 4.6 is broken, I've already tried to find a fix/workaround with another user who had 4.6 and nothing worked.

**Comment by osdalong** [comment]
> > the chinese Pro Eye is differen to global Pro Eye, so there is no update 4.8.x for me.
> 
> You can not install the version from global website? 4.7.5 also works but 4.6 is broken, I've already tried to find a fix/workaround with another user who had 4.6 and nothing worked.

korejan, thank you reply.
cant instatll global version. because the chinese hardware of  Pro Eye is differen to global Pro Eye.
