### ISSUE TITLE
ALXR Pico Version does not work on Pico 4 

### ISSUE THREAD

**Issue by LVNSDCAPE** [korejan/ALVR#50]
I just got the Pico 4 installed ALVR and current ALXR nightly built as also ALXR builds from last weeks and although ALXR is launching on PICO and i see the two cubes there is no passthrough at all using any controller commands.

Non command works here as it is on Quest 2 :( 
Also tried latest ALVR Server nightly built which does not detect the pico 4 anymore so i reversed to ALVR 18.2.3

Am i doing something wrong ? 

And is there a preset for Pico4 which may let it work as it should?

**Comment by korejan** [comment]
Hello, Pico 4 does not currently support the OpenXR extension [`XR_FB_passthrough`](https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XR_FB_passthrough), the only OpenXR runtime to support this currently is the Quest 2/Pro.

Pico's passthrough support for apps right now requires using Pico's own SDK, I may consider using this if it is possible to interop with OpenXR but there is no documentation about this.

ALXR is only compatible with v18.2.3 server at the moment, it will be made compitable with v19 in the near the future.

**Comment by korejan** [comment]
Nightly builds support passthrough modes for Pico headsets.
