### ISSUE TITLE
Pixalations when head is moving using Pico 4 once ALXR is started  

### ISSUE THREAD

**Issue by LVNSDCAPE** [korejan/ALVR#51]
I am experiencing these pixelations whenever i move my head on Pico 4 using ALVR and Pico ALXR: 

Video i recorded in PICO 4 
 https://www.veed.io/view/adfd0f9c-ea59-4688-9f8f-6b7422b743ae?sharingWidget=true

It stops once i shut down ALXR

Current Firmware on PICO 
ALVR 18.2.3 plus latest ALXR Built. 
Also tried elder from last weeks with same result. 

I changed bandwith etc at ALVR but i have no idea what to set at what position. 

RTX 3080 Card with latest drivers.
Windows 10 64 Bit

**Comment by korejan** [comment]
This is happens when using UDP, very recently a way to improve UDP connections was found and I will need to incorporate this. Until then please switch to TCP protocol for stable results.
