### ISSUE TITLE
Some errors happens when I try to build ALXR 0.10 from source codes.

### ISSUE THREAD

**Issue by Hope10086** [korejan/ALVR#53]
## Description

 I  tried to build the ALXR 0.10.0 from source codes  after reading the  ALVR Wikis last weekend. I got apk files named by "alvr_client_oculus_go" and "alvr_client_oculus_quest" .But I'm more concerned  about the apk file on the pico neo.  The PROBLEMS bar of VScode show   "android-ndk-sys only supports compiling for Android"  in  lib.rs whose path is 
"C:/Users/My Username/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-sys-0.4.0/src/lib.rs""

korejan## General Troubleshooting
- [ yes ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [ yes  ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
VScode 1.72 .2
Rust :  rustc   1.64.0 (a55dd71d5 2022-09-19) 
           rustup 1.25.1 (bb60b1e89 2022-07-12)
           cargo  1.64.0 (387270bc7 2022-09-16)
           stable-x86_64-pc-windows-gnu unchanged - rustc 1.64.0 (a55dd71d5 2022-09-19)
           stable-x86_64-pc-windows-msvc unchanged - rustc 1.64.0 (a55dd71d5 2022-09-19)
           nightly-x86_64-pc-windows-msvc updated - rustc 1.67.0-nightly (77e57db38 2022-10-30)
LLVM  14.0.3 
Android studio  2021.3
NDK (Side by side) 25.1.8937393
Android SDK 33（Tiramisu） And  their environment variables have been set  correctly .
- [ √] Source
**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):
 Window 10
## Specific content
 Hello! Dear  author,  I  tried to build the ALXR 0.10.0 from source codes  after reading the  ALVR Wikis last weekend. I got apk files named by "alvr_client_oculus_go" and "alvr_client_oculus_quest" .But I'm more concerned  about the apk file on  the pico neo.  
The  PROBLEMS bar of VScode show   "android-ndk-sys only supports compiling for Android"   in  " lib.rs"  whose path is 
"C:/Users/My Username/.cargo/registry/src/github.com-1ecc6299db9ec823/ndk-sys-0.4.0/src/lib.rs"" 

 The  error  [E0425]  in the  file named by"io.rs', the error [E0599] 、[E0433] in  "lib.rs" also trobule me .I has built the server"ALVR 18.2.3" on VScode patform early.  To my surpirse, I got the"ALVR Launcher.exe" with  error [E0599] 、[E0433]  in "lib.rs"  are shown  on PROBLEMS bar while  the  the"ALVR Launcher.exe"  could run successful.  

I‘m new to the Rust ，and the  Project is complicated . I want to know what's wrong with my  operations and how to build the pico neo 's apk  correctly.

The picture is as following ：
client:
![image](https://user-images.githubusercontent.com/112925968/198958048-2efbadf0-40a9-4aaf-92fb-4e12107c428d.png)
Thank you ！ 
server: 
![image](https://user-images.githubusercontent.com/112925968/198967843-614c4946-86a9-4e38-8fd0-8e23d300c415.png)

**Comment by korejan** [comment]
Hi, you're following the wrong instructions to make alxr builds, you have built the alvr client, please follow the build instructions [here](https://github.com/korejan/ALVR/wiki/ALXR-Client), if you don't need to make changes to the server (and don't need the extra controller emulation profiles) you can just install the release build of v18.2.3 server from the main repository.

**Comment by Hope10086** [comment]
Thank you very much ！ I haven't seen there two "Build from Source" in Wiki. I'll try it right away

**Comment by Hope10086** [comment]
Hello!  I try it just now. When I input “cargo xtask build-alxr-pico”on the TERMNAL ，it reflects “Error: Platform `29` is not installed.”.  Is the "Platform 29" means Android SDK 29? However , Android SDK 33 is mentioned in the Wikis

**Comment by Hope10086** [comment]
> Hi, you're following the wrong instructions to make alxr builds, you have built the alvr client, please follow the build instructions [here](https://github.com/korejan/ALVR/wiki/ALXR-Client), if you don't need to make changes to the server (and don't need the extra controller emulation profiles) you can just install the release build of v18.2.3 server from the main repository.

Hello! I try it just now. When I input “cargo xtask build-alxr-pico”on the TERMNAL ，it reflects “Error: Platform 29 is not installed.”. Is the "Platform 29" means Android SDK 29? However , Android SDK 33 is mentioned in the Wikis
