### ISSUE TITLE
An error about CMake when building.

### ISSUE THREAD

**Issue by Hope10086** [korejan/ALVR#54]
Hey ，Why it reflects ""CMake Error: The source directory  ALVR-0.10.0/alvr/openxr-client/alxr-engine-sys/cpp/ALVR-OpenXR-Engine" does not appear to contain CMakeLists.txt  "" when  I build "openxr-client\alxr-engine-sys\android" in android studio.
I have set install CMake 3.22.1，3.18.1，in the SDK Manager and  operated step by step according to the Wikis.

**Comment by korejan** [comment]
Hey, did you use git to clone the repository? if so you'll need to run `git submodule update --init --recursive` on the root alvr folder. The project is basically divided into 2 repositories, the alvr fork submoduling the "ALVR-OpenXR-Engine" (I need to rename this at some point) repository.

**Comment by Hope10086** [comment]
> Hey, did you use git to clone the repository? if so you'll need to run `git submodule update --init --recursive` on the root alvr folder. The project is basically divided into 2 repositories, the alvr fork submodules the "ALVR-OpenXR-Engine" (I need to rename this at some point) repository.

yes, I have run git submodule update --init --recursive  on the root alvr folder  though noting was shown on the Terminal.
![image](https://user-images.githubusercontent.com/112925968/199221559-e709b5b5-8947-4eed-a576-f611f258ee59.png)

**Comment by Hope10086** [comment]
I hadn't use git to clone the reository .  I  download the zip file by browser,
But I  run git submodule update --init --recursive on the root alvr folder    then  nothing was shown on the Terminal.
![image](https://user-images.githubusercontent.com/112925968/199226694-d10cc13f-8fd6-41c9-80b4-99a8e6c8e6f5.png)

**Comment by Hope10086** [comment]
> > I hadn't use git to clone the reository . I download the zip file by browser, But I run git submodule update --init --recursive on the root alvr folder then nothing was shown on the Terminal. ![image](https://user-images.githubusercontent.com/112925968/199226694-d10cc13f-8fd6-41c9-80b4-99a8e6c8e6f5.png)
> 
> Yeah that won't work this way, you can either use git to clone the repository to your local machine and then git submodule way or if you use github desktop app, it should do this in a single clone.
> 
> If you're planning to make changes it will work out better this way as you may need to sync up to the latest changes in the future.
> 
> Can I ask what it is that you're planning to do?

Thank you, I will have a try. My team is planning to use neural networks to do some video codec optimization on the streaming platform. My job was to run the ALVR  and learn how it worked as detailed as possible  to make sure that future changes that other members added would work.  But I'm still a beginner and I have a  long way to go. Before I became one of team,others use the"ALVR 2.3.1"  .And you know ,there many changes between  “2.3.1”and “18.2.3”.

**Comment by korejan** [comment]
> > > I hadn't use git to clone the reository . I download the zip file by browser, But I run git submodule update --init --recursive on the root alvr folder then nothing was shown on the Terminal. ![image](https://user-images.githubusercontent.com/112925968/199226694-d10cc13f-8fd6-41c9-80b4-99a8e6c8e6f5.png)
> > 
> > 
> > Yeah that won't work this way, you can either use git to clone the repository to your local machine and then git submodule way or if you use github desktop app, it should do this in a single clone.
> > If you're planning to make changes it will work out better this way as you may need to sync up to the latest changes in the future.
> > Can I ask what it is that you're planning to do?
> 
> Thank you, I will have a try. My team is planning to use neural networks to do some video codec optimization on the streaming platform. My job was to run the ALVR and learn how it worked as detailed as possible to make sure that future changes that other members added would work. But I'm still a beginner and I have a long way to go. Before I became one of team,others use the"ALVR 2.3.1" .And you know ,there many changes between “2.3.1”and “18.2.3”.

I see, I should probably inform you that the parent repository is still in active developement too, and there was just a v19 release which has a lot of changes too (I intend to upgrade to it a little later on). ALXR isn't really a port of the ALVR client so the codebases are quite different with support for different devices/API/features.

**Comment by Hope10086** [comment]
> Hey, did you use git to clone the repository? if so you'll need to run `git submodule update --init --recursive` on the root alvr folder. The project is basically divided into 2 repositories, the alvr fork submodules the "ALVR-OpenXR-Engine" (I need to rename this at some point) repository.

**Yesterday** ，I could   build  project whose path is"\alvr\openxr-client\alxr-engine-sys\app"  successfully    on  the Android-studio.
(All platforms could be build  successfully   ).
But the  Terminal  still stop at "Building []  261/265:alxr-engine-sys(build)".

So,today I remove all projects and files then  git clone source codes in a new folder.
I have run “ git submodule update --init --recursive”  ，then Terminal shows "" check out  "fca43fa......"  "" . 
I guess it's successful . However，I got error about Cmake on Android-studio. when I try to build "\alvr\openxr-client\alxr-engine-sys\app"  .  


![image](https://user-images.githubusercontent.com/112925968/199670740-e89c78ff-7ca8-4e96-b81b-7ab658231e39.png)

**Comment by Hope10086** [comment]
> **Yesterday** ，I could build project whose path is"\alvr\openxr-client\alxr-engine-sys\app" successfully on the Android-studio. (All platforms could be build successfully ). But the Terminal still stop at "Building [] 261/265:alxr-engine-sys(build)".
> 
> **So,today** I remove all projects and files then git clone source codes in a new folder. I have run “ git submodule update --init --recursive” ，then Terminal shows "" check out "fca43fa......" "" . I guess it's successful . However，I got error about Cmake on Android-studio. when I try to build "\alvr\openxr-client\alxr-engine-sys\app" .
![image](https://user-images.githubusercontent.com/112925968/199673936-b33ccbce-30a2-4e92-957b-491ed9b84d08.png)

**Comment by korejan** [comment]
> > **Yesterday** ，I could build project whose path is### "### _alvr\openxr-client\alxr-engine-sys\android_" successfully on the Android-studio. (All platforms could be build successfully ). But the Terminal still stop at "Building [] 261/265:alxr-engine-sys(build)".
> > **So,today** I remove all projects and files then git clone source codes in a new folder. I have run “ git submodule update --init --recursive” ，then Terminal shows "" check out "fca43fa......" "" . I guess it's successful . However，I got error about Cmake on Android-studio. when I try to build "_alvr\openxr-client\alxr-engine-sys\android"_ .
> > ![image](https://user-images.githubusercontent.com/112925968/199673936-b33ccbce-30a2-4e92-957b-491ed9b84d08.png)

This happens sometimes when github is down or similllar, it's failing to fetch a github dependenciey, if you go to the menu and run "Build" -> "Refresh Linked C++ Projects" to try again, if it keeps on happening, delete the folders inside of `alxr-engine-sys\android\app\.cxx` and run "Refresh Linked C++ Projects".

The hang on building alxr-engine-sys, is known issuse when building on windows only, you can find the workarounds in ["please note"](https://github.com/korejan/ALVR/wiki/ALXR-Client#dev-builds-for-android-any-flavor) paragraph

**Comment by Nidy** [comment]
When i run "Build" -> "Refresh Linked C++ Projects" , i got this error, any idea for this issue? @korejan 

> Task :prepareKotlinBuildScriptModel UP-TO-DATE
C/C++: OculusMobileOXRDebug|arm64-v8a :Found glslc: D:/Android/sdk/ndk/25.1.8937393/shader-tools/windows-x86_64/glslc.exe
C/C++: OculusMobileOXRDebug|arm64-v8a :CMake Error at src/CMakeLists.txt:610 (message):
C/C++: OculusMobileOXRDebug|arm64-v8a :  Python 3 not found, but pre-generated
C/C++: OculusMobileOXRDebug|arm64-v8a :  E:/Code/ALVR/alvr/openxr-client/alxr-engine-sys/cpp/ALVR-OpenXR-Engine/src/xr_generated_dispatch_table.h
C/C++: OculusMobileOXRDebug|arm64-v8a :  not found
C/C++: OculusMobileOXRDebug|arm64-v8a :Call Stack (most recent call first):
C/C++: OculusMobileOXRDebug|arm64-v8a :  src/CMakeLists.txt:663 (run_xr_xml_generate)
[CXX1405] error when building with cmake using E:\Code\ALVR\alvr\openxr-client\alxr-engine-sys\cpp\ALVR-OpenXR-Engine\CMakeLists.txt: Build command failed.
Error while executing process D:\Android\sdk\cmake\3.22.1\bin\cmake.exe with arguments {-HE:\Code\ALVR\alvr\openxr-client\alxr-engine-sys\cpp\ALVR-OpenXR-Engine -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=28 -DANDROID_PLATFORM=android-28 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=D:\Android\sdk\ndk\25.1.8937393 -DCMAKE_ANDROID_NDK=D:\Android\sdk\ndk\25.1.8937393 -DCMAKE_TOOLCHAIN_FILE=D:\Android\sdk\ndk\25.1.8937393\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\Android\sdk\cmake\3.22.1\bin\ninja.exe -DCMAKE_CXX_FLAGS=-std=c++20 -fexceptions -frtti -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=E:\Code\ALVR\alvr\openxr-client\alxr-engine-sys\android\app\build\intermediates\cxx\Debug\330611m5\obj\arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=E:\Code\ALVR\alvr\openxr-client\alxr-engine-sys\android\app\build\intermediates\cxx\Debug\330611m5\obj\arm64-v8a -DCMAKE_BUILD_TYPE=Debug -BE:\Code\ALVR\alvr\openxr-client\alxr-engine-sys\android\app\.cxx\Debug\330611m5\arm64-v8a -GNinja -DPython_ROOT_DIR='C:/Users/korcan/AppData/Local/Programs/Python/Python310' -DANDROID_ARM_NEON=TRUE -DBUILD_API_LAYERS=OFF -DBUILD_TESTS=OFF -DBUILD_CONFORMANCE_TESTS=OFF -DBUILD_ALL_EXTENSIONS=ON -DBUILD_LOADER=OFF -DUSE_OCULUS_MOBILE_LOADER=ON}
-- The C compiler identification is Clang 14.0.6
-- The CXX compiler identification is Clang 14.0.6
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: D:/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: D:/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find PythonInterp (missing: PYTHON_EXECUTABLE) (Required is at least version "3")
-- Performing Test HAVE_FILESYSTEM_IN_STD
-- Performing Test HAVE_FILESYSTEM_IN_STD - Success
-- Performing Test HAVE_FILESYSTEM_IN_STDEXPERIMENTAL
-- Performing Test HAVE_FILESYSTEM_IN_STDEXPERIMENTAL - Failed
-- Performing Test HAVE_FILESYSTEM_IN_STD_17
-- Performing Test HAVE_FILESYSTEM_IN_STD_17 - Success
-- Performing Test HAVE_FILESYSTEM_WITHOUT_LIB
-- Performing Test HAVE_FILESYSTEM_WITHOUT_LIB - Success
-- Performing Test HAVE_FILESYSTEM_NEEDING_LIBSTDCXXFS
-- Performing Test HAVE_FILESYSTEM_NEEDING_LIBSTDCXXFS - Failed
-- Performing Test HAVE_FILESYSTEM_NEEDING_LIBCXXFS
-- Performing Test HAVE_FILESYSTEM_NEEDING_LIBCXXFS - Failed
-- Found OpenGLES: D:/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/28/libGLESv3.so  found components: V3 V2 
-- Found PkgConfig: C:/ProgramData/chocolatey/bin/pkg-config.exe (found version "0.28") 
-- Performing Test HAVE_EGL
-- Performing Test HAVE_EGL - Success
-- Found EGL: D:/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/include (found version "1.5") 
-- Enabling OpenGL|ES support
-- Found Vulkan: D:/Android/sdk/ndk/25.1.8937393/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/28/libvulkan.so  
-- Enabling Vulkan support
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Could NOT find JsonCpp (missing: JsonCpp_INCLUDE_DIR JsonCpp_LIBRARY) 
-- Enabling OpenGL support in hello_xr, loader_test, and conformance, if configured
-- Looking for secure_getenv
-- Looking for secure_getenv - not found
-- Looking for __secure_getenv
-- Looking for __secure_getenv - not found
-- Configuring incomplete, errors occurred!
See also "E:/Code/ALVR/alvr/openxr-client/alxr-engine-sys/android/app/.cxx/Debug/330611m5/arm64-v8a/CMakeFiles/CMakeOutput.log".
See also "E:/Code/ALVR/alvr/openxr-client/alxr-engine-sys/android/app/.cxx/Debug/330611m5/arm64-v8a/CMakeFiles/CMakeError.log".

Found glslc: D:/Android/sdk/ndk/25.1.8937393/shader-tools/windows-x86_64/glslc.exe
CMake Error at src/CMakeLists.txt:610 (message):
  Python 3 not found, but pre-generated
  E:/Code/ALVR/alvr/openxr-client/alxr-engine-sys/cpp/ALVR-OpenXR-Engine/src/xr_generated_dispatch_table.h
  not found
Call Stack (most recent call first):
  src/CMakeLists.txt:663 (run_xr_xml_generate)
