### ISSUE TITLE
Process didn't exit successfully:

### ISSUE THREAD

**Issue by Hope10086** [korejan/ALVR#55]
## Description

An error  occured  caused by **Process didn't exit successfully:**   when building  command for `alxr-engine-sys v0.10.0.

## Environement

**OS Name and Version** 
Ubuntu 18.04.6LTS ( on the VMware  virtual machine)
Rust，cargo ，LLVM ,Android-studio and its  SDK 、NDK  Cmake etc are  up to date .
Python3.9
## Details
Hey! I am the beginner who consulted the _"`git submodule update --init --recursive`"_  not a long ago.
I failed to build the alxr on the Windows10 ,so I have a try  on the linux by VMware .
However,there  still are erros when building`alxr-engine-sys '
Terminal still hang out when building `alxr-engine-sys ‘  then I open the  folder named `alxr-engine-sys ' . It could be build successfully  on all platform .

But the terminal would show 
_```

> "failed to run custom build command for `alxr-engine-sys v0.10.0 (/home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/alvr/openxr-client/alxr-engine-sys)`
> Caused by:
>   process didn't exit successfully: `/home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/target/debug/build/alvr_filesystem-412ecd03828ff32d/out/../../../../quest/debug/build/alxr-engine-sys-b96e03c395b8335e/build-script-build` (exit status: 101)

```_
".
```

Of cource there are also a lot of specific information  is printed  later .I can't get some useful texts.

I guess  the   reason is  OpenJDK Platform binary process didn't exit. It's right?
What should I do?
```

**Comment by korejan** [comment]
Which command did you use to build? if you're using `cargo build` / `cargo apk` you can add the flag `-vv` (for very verbose) to get more useful error message.

**Comment by Hope10086** [comment]
Now, I use command` cargo apk build -p alxr-client-pico -vv` to build.

I get the information ——————
```
[alxr-engine-sys 0.10.0] selected product flavor: PicoMobileOXR
[alxr-engine-sys 0.10.0] > Task :app:preBuild UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:prePicoMobileOXRDebugBuild UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugAidl NO-SOURCE
[alxr-engine-sys 0.10.0] > Task :app:configureCMakeDebug[arm64-v8a]-3
[alxr-engine-sys 0.10.0] > Task :app:buildCMakeDebug[arm64-v8a]-3
[alxr-engine-sys 0.10.0] > Task :app:configureCMakeDebug[armeabi-v7a]-2
[alxr-engine-sys 0.10.0] > Task :app:buildCMakeDebug[armeabi-v7a]-2
[alxr-engine-sys 0.10.0] > Task :app:externalNativeBuildPicoMobileOXRDebug
[alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugJniLibFolders UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugNativeLibs UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:stripPicoMobileOXRDebugDebugSymbols UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:copyPicoMobileOXRDebugJniLibsProjectAndLocalJars UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugRenderscript NO-SOURCE
[alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugBuildConfig UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugResValues UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugResources UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:packagePicoMobileOXRDebugResources UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:parsePicoMobileOXRDebugLocalResources UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:processPicoMobileOXRDebugManifest UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugRFile UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugKotlin NO-SOURCE
[alxr-engine-sys 0.10.0] > Task :app:extractPicoMobileOXRDebugAnnotations UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:javaPreCompilePicoMobileOXRDebug UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugJavaWithJavac UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugGeneratedProguardFiles UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugConsumerProguardFiles UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugShaders UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugShaders NO-SOURCE
[alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugAssets UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:packagePicoMobileOXRDebugAssets UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:packagePicoMobileOXRDebugRenderscript NO-SOURCE
[alxr-engine-sys 0.10.0] > Task :app:prepareLintJarForPublish UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:preparePicoMobileOXRDebugArtProfile UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:processPicoMobileOXRDebugJavaRes NO-SOURCE
[alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugJavaResource UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:syncPicoMobileOXRDebugLibJars UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:writePicoMobileOXRDebugAarMetadata UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:bundlePicoMobileOXRDebugAar UP-TO-DATE
[alxr-engine-sys 0.10.0] > Task :app:assemblePicoMobileOXRDebug UP-TO-DATE
[alxr-engine-sys 0.10.0] 
[alxr-engine-sys 0.10.0] BUILD SUCCESSFUL in 1s
```
## Above is same as the information on Android-studio.
## The following may be useful.
```
[alxr-engine-sys 0.10.0] 28 actionable tasks: 5 executed, 23 up-to-date
[alxr-engine-sys 0.10.0] clang diag: /home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/alvr/openxr-client/alxr-engine-sys/cpp/ALVR-OpenXR-Engine/src/alxr_engine/alxr_engine.h:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
[alxr-engine-sys 0.10.0] thread 'main' panicked at 'bindings: ClangDiagnostic("error: invalid value 'c++20' in '-std=c++20'\n")', alvr/openxr-client/alxr-engine-sys/build.rs:263:10
[alxr-engine-sys 0.10.0] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `alxr-engine-sys v0.10.0 (/home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/alvr/openxr-client/alxr-engine-sys)`

Caused by:
  process didn't exit successfully: `/home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/target/debug/build/alxr-engine-sys-99df2e8a72d18566/build-script-build` (exit status: 101)

```

**Comment by korejan** [comment]
> Now, I use command` cargo apk build -p alxr-client-pico -vv` to build.
> 
> I get the information ——————
> 
> ```
> [alxr-engine-sys 0.10.0] selected product flavor: PicoMobileOXR
> [alxr-engine-sys 0.10.0] > Task :app:preBuild UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:prePicoMobileOXRDebugBuild UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugAidl NO-SOURCE
> [alxr-engine-sys 0.10.0] > Task :app:configureCMakeDebug[arm64-v8a]-3
> [alxr-engine-sys 0.10.0] > Task :app:buildCMakeDebug[arm64-v8a]-3
> [alxr-engine-sys 0.10.0] > Task :app:configureCMakeDebug[armeabi-v7a]-2
> [alxr-engine-sys 0.10.0] > Task :app:buildCMakeDebug[armeabi-v7a]-2
> [alxr-engine-sys 0.10.0] > Task :app:externalNativeBuildPicoMobileOXRDebug
> [alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugJniLibFolders UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugNativeLibs UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:stripPicoMobileOXRDebugDebugSymbols UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:copyPicoMobileOXRDebugJniLibsProjectAndLocalJars UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugRenderscript NO-SOURCE
> [alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugBuildConfig UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugResValues UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugResources UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:packagePicoMobileOXRDebugResources UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:parsePicoMobileOXRDebugLocalResources UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:processPicoMobileOXRDebugManifest UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugRFile UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugKotlin NO-SOURCE
> [alxr-engine-sys 0.10.0] > Task :app:extractPicoMobileOXRDebugAnnotations UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:javaPreCompilePicoMobileOXRDebug UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugJavaWithJavac UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugGeneratedProguardFiles UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugConsumerProguardFiles UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugShaders UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:compilePicoMobileOXRDebugShaders NO-SOURCE
> [alxr-engine-sys 0.10.0] > Task :app:generatePicoMobileOXRDebugAssets UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:packagePicoMobileOXRDebugAssets UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:packagePicoMobileOXRDebugRenderscript NO-SOURCE
> [alxr-engine-sys 0.10.0] > Task :app:prepareLintJarForPublish UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:preparePicoMobileOXRDebugArtProfile UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:processPicoMobileOXRDebugJavaRes NO-SOURCE
> [alxr-engine-sys 0.10.0] > Task :app:mergePicoMobileOXRDebugJavaResource UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:syncPicoMobileOXRDebugLibJars UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:writePicoMobileOXRDebugAarMetadata UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:bundlePicoMobileOXRDebugAar UP-TO-DATE
> [alxr-engine-sys 0.10.0] > Task :app:assemblePicoMobileOXRDebug UP-TO-DATE
> [alxr-engine-sys 0.10.0] 
> [alxr-engine-sys 0.10.0] BUILD SUCCESSFUL in 1s
> ```
> 
> #Above is same as the information on Android-studio. #The following may be useful.
> 
> ```
> [alxr-engine-sys 0.10.0] 28 actionable tasks: 5 executed, 23 up-to-date
> [alxr-engine-sys 0.10.0] clang diag: /home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/alvr/openxr-client/alxr-engine-sys/cpp/ALVR-OpenXR-Engine/src/alxr_engine/alxr_engine.h:1:9: warning: #pragma once in main file [-Wpragma-once-outside-header]
> [alxr-engine-sys 0.10.0] thread 'main' panicked at 'bindings: ClangDiagnostic("error: invalid value 'c++20' in '-std=c++20'\n")', alvr/openxr-client/alxr-engine-sys/build.rs:263:10
> [alxr-engine-sys 0.10.0] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> error: failed to run custom build command for `alxr-engine-sys v0.10.0 (/home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/alvr/openxr-client/alxr-engine-sys)`
> 
> Caused by:
>   process didn't exit successfully: `/home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/target/debug/build/alxr-engine-sys-99df2e8a72d18566/build-script-build` (exit status: 101)
> ```

Which version of llvm/libclang do you have installed? it seems like an old version that doesn't support compiling in C++20 mode but considering that the header that is being parsed is suppose to be a C interface for rust you try commenting out this line: 
![image](https://user-images.githubusercontent.com/64199710/199771002-c44b2b17-46f8-46b8-a0ba-fba1bdcb2396.png)
in `alvr/openxr-client/alxr-engine-sys/build.rs`

> I would like to know if there are any requirements of computer graphics card for compiling "ALXR" .

For compiling none, for running it dpeends on which platform/device.

**Comment by Hope10086** [comment]
I commented  out `".clang_arg("-stc=c++20")" .`
Then the progress "build  alxr-engine-sys  " is successful .
Then  the terminal would  show：
```
verification succesful
/home/sunhaonan/Android/Sdk/build-tools/33.0.0/apksigner:line 97 : exec: java: not found
**Error**: Command `/home/sunhaonan/Android/Sdk/build-tools/33.0.0/apksigner sign --ks /home/sunhaonan/.android/debug.keystore --ks-pass 
pass:android /home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/target/debug/apk/alxr-client-pico.apk` had a non-ze
```
 After reading it，I open the folder   mentioned above. There are two 'apk'files named by "alxr-client-pico.apk"and "alxr-client-pico-unaligned.apk" .（I guess they are  the files  that I want to get.I wil take a test right now）. 
I  removed them   to a folder that has nothing with "ALVR"  then  build it with  command "`cargo apk build -p alxr-client-pico -vv`"again. After that ,  the terminal would  show the same information and stop .

I want to know if the build process is over or  there are other steps .
Are my processes and results normal ？

**Comment by Hope10086** [comment]
The code in appsigner  `exec java $javaOpts -jar "$jarpath" "$@"` is  not working.
Maybe I need to change the path of java or the code above  to keep  them in line .
I

**Comment by Hope10086** [comment]
The line 97:`exec java $javaOpts -jar "$jarpath" "$@"` in "appsigner"   is not working.
Maybe I need to change my java 'path  of change the code above to make them in line

**Comment by Hope10086** [comment]
I add the `JAVA_HOME/bin` to `PATH` , `JAVA_HOME/lib `to `CLASSPATH`  in the  Environment Variable.
Then  it become like this:
```
Error: Could not find or load main class .opt.android-studio.jre
Caused by: java.lang.ClassNotFoundException: /opt/android-studio/jre
Error: Command `/home/sunhaonan/Android/Sdk/build-tools/33.0.0/apksigner sign --ks /home/sunhaonan/.android/debug.keystore --ks-pass pass:android /home/sunhaonan/CloudGame/Build_Android-studio/Test3/ALVR/target/debug/apk/alxr-client-pico.apk` had a non-zero exit code.

```
This was a Java-related error, but I didn't make any additional changes.
