### ISSUE TITLE
Pico 4 image lags behind head movement.

### ISSUE THREAD

**Issue by Yersi88** [korejan/ALVR#56]
## Description

In all games, so afar i tested: Steamvr home, beat saber, vr chat, steam overlay. 

The image lags behind head movement. Image follow after the head is turned. But, controller movement is instant. 

![image](https://user-images.githubusercontent.com/77145281/200128664-5c9e4d0e-6267-4a03-b865-94e659c98c9a.png)
here is some latency stats. 

## General Troubleshooting
- [x ] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x ] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Hardware
![image](https://user-images.githubusercontent.com/77145281/200128318-8e0872fe-b49a-4161-aebf-be091c42fa7b.png)

### Installation
**ALVR Version**:
18.2.3
**SteamVR Version**:
beta 1.24.6

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ x] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions):Arch Linux x86_64

**Comment by Timocop** [comment]
Same happens on Pico Neo 3 Link. The image has a noticeable delay controllers move fine.

https://user-images.githubusercontent.com/22834512/200149247-a83e456e-7737-4711-ba64-31de9b818231.mp4

**Comment by Yersi88** [comment]
> Same happens on Pico Neo 3 Link. The image has a noticeable delay controllers move fine.
> zhthjdfghedftudfg.mp4

This is EXACTLY how it looks on my Pico 4!

**Comment by Timocop** [comment]
This is happening on my Windows 10 machine btw. Forgot to mention

**Comment by Yersi88** [comment]
@svsdval I don't know actually! As you can see on my neofetch above, I'm on Arch and Zen kernel. Not sure that has anything to do with it tho. I assume we're on the same proprietary nvidia driver.

**Comment by korejan** [comment]
This is now been [fixed](https://github.com/korejan/ALVR/commit/ec8f197416f5d02f182df9085a4d60785066c2ca)
