### ISSUE TITLE
Quest Pro EyeTracker not working

### ISSUE THREAD

**Issue by Kieaer** [korejan/ALVR#65]
## Description

![image-2](https://user-images.githubusercontent.com/44261958/207102811-fbc29e9f-5f90-4bd3-bac9-5693ee2da81e.png)

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

## Environement
ALXR Version: v0.10.0+nightly.2022.12.11

### Hardware
Using RTX 4090. ALXR says its not a minimum spec.

**Install Type**:
- [x] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [ ] Source

**OS Name and Version** (`winver` on Windows or `grep PRETTY_NAME /etc/os-release` on most Linux distributions): Windows 11 22H2

**Comment by korejan** [comment]
Hello, this is the wrong build for Facial & Eye tracking, the builds for these are currently in the [ALXR-experimental](https://github.com/korejan/ALXR-experimental/releases). For more details/instructions please [read here](https://github.com/korejan/ALVR/discussions/62)
