### ISSUE TITLE
Quest 2 client light green screen only

### ISSUE THREAD

**Issue by COZMIKDX** [korejan/ALVR#67]
I have installed the v0.10.0 alxr-client-quest.apk file on my quest 2 using sidequest.
My quest 2 on update v47.

After launching the client all that is displayed is a pale green screen with no menus, ip address display, etc.
None of the controller buttons change this either.

**Comment by korejan** [comment]
@COZMIKDX Hello, there is no lobby screen or UI currently, this is how it looks when there's no stream, lobby screen/UI is coming in the future. For the time being please use the [nightly builds](https://github.com/korejan/ALXR-nightly/releases) instead and use the v18.2.3 ALVR server, v19 is not currently supported.

**Comment by COZMIKDX** [comment]
Sorry for the late response.
Switching to server v18.2.3 worked and all seems to be running fine.
Thanks for the help.
