### ISSUE TITLE
Testing ALXR client on Meta Quest Pro

### ISSUE THREAD

**Issue by rtrimana** [korejan/ALVR#75]
Hi @korejan,

Thanks so much for providing the experimental build for eye and facial expression tracking on the new Meta Quest Pro headset. I am thinking of testing it out. Could you please kindly confirm that the below steps would be the correct way to enable and test it on the headset? I also have some questions below.

- Use the stable version from the nightly builds of the ALXR client [here](https://github.com/korejan/ALXR-experimental), namely use [alxr-client-quest.apk](https://github.com/korejan/ALVR/releases/download/v0.10.0/alxr-client-quest.apk)
- Install ALVR server on, say, a Windows 10 PC, as suggested [here](https://github.com/korejan/ALVR/wiki/ALXR-Client#all-versions). The Wiki suggests server v18.2.3 as of writing. 

Questions: 
- Would it be a problem if I used ALVR server v19.0.0 that's provided [here](https://github.com/alvr-org/ALVR/releases/tag/v19.0.0), for example?
- Do you have any thoughts about which app on Meta Quest Pro that we can use to test the eye/facial expression tracking feature in this case?

Thank you so much in advance for your help.

**Comment by DaniruKun** [comment]
I never got the client to even connect on `v19.0.0`, but `v18.2.3` worked instantly.
ALVR works fine on Windows 11 for me, and VRCFT finds the Quest Pro, but I get 0 OSC data in VRC and nothing in the preview tabs.

**Comment by rtrimana** [comment]
Thank you so much for this information @DaniruKun ! I really appreciate it.

**Comment by korejan** [comment]
@rtrimana Currently the only apps that connect to ALXR for Quest pro facial & eye tracking are vrchat via vrcft and NeosVR via plugin, other apps can easily add support.

The stable release builds do not have facial & eye tracking support, and currently the latest stable release is quite old and very far build nightly builds. Please read [here](https://github.com/korejan/ALVR/discussions/62) for further details & instructions on using Quest Pro F&E tracking.

@DaniruKun I had confirmation that latest f&e tracking builds from ALXR-experimental repo is working.

**Comment by rtrimana** [comment]
Thanks so much for this information @korejan . I really appreciate it.
