### ISSUE TITLE
ALXR Client on Pico 4 does not display any Interface

### ISSUE THREAD

**Issue by ZhenyaPav** [korejan/ALVR#77]
I am currently having the same issue as described in alvr-org/ALVR#1337, not being able to launch the client properly.
It doesn't display anything other than the two default cubes and the Alvr server also doesn't detect it.
![209954129-cbf2b3c5-8b84-448d-8a4d-df77b16022dd](https://user-images.githubusercontent.com/61346893/219818093-96fdf6b3-99ff-4195-8ccb-918f6b0107d0.jpeg)

**Comment by korejan** [comment]
@ZhenyaPav Hi, this is how it currently looks when there is no stream, a custom "lobby" screen and UI is planned. Which version of the alvr server are you using? currently only v18.2.3 is supported, v19/20 support will come in the near the future. If you are using v18.2.3 on windows and the client is not discovered make sure windows network discovery is enable, you can also manually add client IP address.

**Comment by ZhenyaPav** [comment]
I've used the wrong server version, it works with 18.2.3. However there is significant latency, and unlike VD and AirLink, it seems to affect rotation as well, so unfortunately it's not very usable rn.

**Comment by korejan** [comment]
> I've used the wrong server version, it works with 18.2.3. However there is significant latency, and unlike VD and AirLink, it seems to affect rotation as well, so unfortunately it's not very usable rn.

@ZhenyaPav which version of ALXR are you using? if you're not already using it please use latest[ nightly builds](https://github.com/korejan/ALXR-nightly/releases), the last stable release is very out of date. Also consider tweaking the controller position & rotation offsets in the ALVR dashboard with advance options on, the default values were set for the original v18 client on a quest with different api.

**Comment by korejan** [comment]
> > I've used the wrong server version, it works with 18.2.3. However there is significant latency, and unlike VD and AirLink, it seems to affect rotation as well, so unfortunately it's not very usable rn.
> 
> @ZhenyaPav which version of ALXR are you using? if you're not already using it please use latest[ nightly builds](https://github.com/korejan/ALXR-nightly/releases), the last stable release is very out of date. Also consider tweaking the controller position & rotation offsets in the ALVR dashboard with advance options on, the default values were set for the original v18 client on a quest with different api.

@ZhenyaPav I forgot to mention as well as the above, use TCP connection. UDP connection are not stable and cause visual artifacts in v18.

**Comment by ZhenyaPav** [comment]
> > I've used the wrong server version, it works with 18.2.3. However there is significant latency, and unlike VD and AirLink, it seems to affect rotation as well, so unfortunately it's not very usable rn.
> 
> @ZhenyaPav which version of ALXR are you using? if you're not already using it please use latest[ nightly builds](https://github.com/korejan/ALXR-nightly/releases), the last stable release is very out of date. Also consider tweaking the controller position & rotation offsets in the ALVR dashboard with advance options on, the default values were set for the original v18 client on a quest with different api.

I've used the version [v0.10.0+nightly.2023.02.18](https://github.com/korejan/ALXR-nightly/releases/tag/v0.10.0%2Bnightly.2023.02.18). The issue with rotational latency is still here, however the client also crashes after about 20 seconds.

**Comment by korejan** [comment]
> > > I've used the wrong server version, it works with 18.2.3. However there is significant latency, and unlike VD and AirLink, it seems to affect rotation as well, so unfortunately it's not very usable rn.
> > 
> > 
> > @ZhenyaPav which version of ALXR are you using? if you're not already using it please use latest[ nightly builds](https://github.com/korejan/ALXR-nightly/releases), the last stable release is very out of date. Also consider tweaking the controller position & rotation offsets in the ALVR dashboard with advance options on, the default values were set for the original v18 client on a quest with different api.
> 
> I've used the version [v0.10.0+nightly.2023.02.18](https://github.com/korejan/ALXR-nightly/releases/tag/v0.10.0%2Bnightly.2023.02.18). The issue with rotational latency is still here, however the client also crashes after about 20 seconds.

@ZhenyaPav which PUI version do you have installed? when you say rotational latency are you referring to headset or controllers?

Something else i forgot to mention is that in the recently released PUI 5.4.x, a long standing bug in Pico's OpenXR runtime has been fixed but in previous versions I have a workaround that I need to disable. This new version also introduced a new issue that effects the colour output. I will be working on these today. If you don't mind could post a copy of your sessions.json so I can see & testing the settings you used.

**Comment by ZhenyaPav** [comment]
@korejan I am referring to headset rotation. The PUI version is 5.3.2 
I've attached the session.json
[session.json.txt](https://github.com/korejan/ALVR/files/10785173/session.json.txt)
