### ISSUE TITLE
[Pico 4] Client can't connect to server

### ISSUE THREAD

**Issue by chayleaf** [korejan/ALVR#78]
## Description

Pico firmware version: 5.3.1. Client: [nightly.2023.02.19/alxr-client-pico.apk](https://github.com/korejan/ALXR-nightly/releases/download/v0.10.0%2Bnightly.2023.02.19/alxr-client-pico.apk).

[Logcat](https://gist.github.com/chayleaf/e3fdc32e19d1306dddc54a74a2fb0078).

The actual problem is that the client isn't able to connect to the ALVR server. I can open it just fine, but can't get past the loading screen with controllers as cubes. On the link above there are two logs - `wifi.logcat` (the client can't see the server at all via wifi), and `adb.logcat` (when connected via adb port forwarding).

## General Troubleshooting
- [x] I carefully followed the instructions in the [README](https://github.com/alvr-org/ALVR/blob/master/README.md) and successfully completed the setup wizard
- [x] I read the ALVR Wikis [here](https://github.com/polygraphene/ALVR/wiki) and [here](https://github.com/alvr-org/ALVR/wiki)

### Installation
**ALVR server Version**: 20.0.0-dev07

**SteamVR Version**: beta 1.25.3

**Install Type**:
- [ ] Packaged (`exe`, `deb`, `rpm`, etc)
- [ ] Portable (`zip`)
- [x] Source (AUR, alvr-git)

**OS Name and Version**: Arch Linux

**Comment by chayleaf** [comment]
ALVR nightly works, so this irrelevant for me now

**Comment by korejan** [comment]
Hi, only v18.2.3 alvr server is supported currently. v19/20 support will come later.
