### ISSUE TITLE
There are a few things I want to confirm with you about Oculus Quest Pro ’s facial-Eye-tracking extension:

### ISSUE THREAD

**Issue by Hope10086** [korejan/ALVR#82]
This week, I studied the client-related code files in the branch `facial-eye-tracking`. By comparing with the master, I found that some functions related to facial eye tracking were added to the related files used to generate `alxr-engine-sys.so`.   However, compared to master, the files under the path:   `alvr\client\android\app\src\main\cpp & java`   didn't seem to change significantly, and there is no information related to face tracking and eye tracking in function `sendTrackingInfo` in file `alvr\client\android\app\src\main\cpp\ovr_context.cpp` . So, I want to cofirm with you :

1. First of all, I was wondering if your team is still in the stage of adding and configuring the facial eye tracking extension for different VR devices, but not adding the higher level code to enable the `facial eye tracking` interaction (What I understand is sending the tracking data back to the `server,` which sends the data to `SteamVR` later for interaction or uses the data to perform foveated rendering ).  And  are you going to do that in the future?
2.  I wonder how the function in the path： `alvr\client\android\app\src\main\cpp`   is implemented to call the function in `alxr-engine-sys.so`?  I didn't find the usual c++ function family for calling`.so` files:` dlopen/dlsym/dlclose`.  
3. I noticed that in the `Oculus mobile openXR SDK` examples, the library loaded by` System.loadLibrary` in `java\MainActivity.java` is implemented by the function `ENTRY_POINT(Xr******App)` at the end of `src\main.c`.  So, in ALXR ,how is the system library  `"alvr_client" ` generated   which is loaded in `alvr\client\android\app\src\main\java\OvrActivity.java`'s` System.loadLibrary("alvr_client")` ?
4. I know that the final client apk file consists of three` .so `files: `libalxr_client_pico/quest.so`, `libalxr_engine.so` and `libopenxr_loader.so` and  an `.xml` file for  configuration. This is my understanding of the hierarchy between them. Is this correct?

**Comment by korejan** [comment]
@Hope10086 You're looking in the wrong place, everything in `alvr\client` is the old v18 ALVR client, ALXR (client) is not a port it is a different code base and it does not have any Java code, only Rust & C/C++. The only place you need to be looking at is in `alvr\openxr-client` folder and sub-folders in there.

The project is split into two main parts the "engine"/C++ library part which is in a seperate [repository](https://github.com/korejan/ALVR-OpenXR-Engine), submoduled into my ALVR repostiory fork and the part that makes up the executables (& handles networking) for different platforms.

In `alvr\openxr-client\alxr-client` this folder deals with generated clients for desktop OSs (Windows/Linux wired/DIY headsets, hololens 2).

 `alvr\openxr-client\alxr-android-client` deals with generate clients for android-based devices.

Anyway as long as you've init & synced the engine submodule, everything you need to look at is in `alvr\openxr-client`

Note I now have new-ish branch, branching off of `facial-eye-tracking` called `facial-eye-refactor` where I've been adding more facial & eye-tracking extensions like `XR_EXT_eye_gaze_interaction` and refactoring the packet format that sends to apps like vrcft.

**Comment by Hope10086** [comment]
Thanks， as I research deeper into your client code this week, I realized some of the mistakes I made earlier.   I noticed the file: `alxr_engine.cpp`, which is the top-level code of the ALXR client. What is the role of the RustCtxPtr structure used? Does it correspond to something in  ` alxr-engine-sys` 's `lib.rs` and  `build.rs` ?

**Comment by korejan** [comment]
> Thanks， as I research deeper into your client code this week, I realized some of the mistakes I made earlier. I noticed the file: `alxr_engine.cpp`, which is the top-level code of the ALXR client. What is the role of the `RustCtxPtr` structure used? Does it correspond to something in ` alxr-engine-sys` 's `lib.rs` and `build.rs` ?

It's okay not your fault, it's not really documentated and it's a bit messy atm i need to do a bit of clean-up at some point. RustCtx is just an init structure, there's some function pointers that need to be setup on the Rust side of code.

If you check the `main/run` functions in `openxr-client\alxr-android-client\src\lib.rs` or `openxr-client\alxr-client\src\main.rs`  that's entry points of the executable which will create instance of `RustCtx` and passes to `alxr_init`.

I'm ill at the moment so I don't know i'll be able to respond further this weekend.

**Comment by Hope10086** [comment]
Thanks for your reply and have a good rest this weekend . 
 I wish you will have a speedy recovery
